<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- React并没有将标记与逻辑进行分离到不同的文件中 -->
    <meta charset="UTF-8" />
    <script
      crossorigin
      src="https://unpkg.com/react@16/umd/react.development.js"
    ></script>
    <script
      crossorigin
      src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"
    ></script>
    <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
  </head>
  <body>
    <div id="root"></div>
    <script type="text/babel">
      /* 错误边界是一种 React 组件，这种组件可以捕获并打印发生在其子组件树任何位置的 JavaScript 错误，并且，它会渲染出备用 UI，而不是渲染那些崩溃了的子组件树。错误边界在渲染期间、生命周期方法和整个组件树的构造函数中捕获错误。 
      错误边界无法捕获以下场景中产生的错误：
      事件处理（了解更多）
      异步代码（例如 setTimeout 或 requestAnimationFrame 回调函数）
      服务端渲染
      它自身抛出来的错误（并非它的子组件）
      */
      class ErrorBoundary extends React.Component {
        constructor(props) {
          super(props);
          this.state = { hasError: false };
        }

        /* 如果一个 class 组件中定义了 static getDerivedStateFromError() 或 componentDidCatch() 这两个生命周期方法中的任意一个（或两个）时，那么它就变成一个错误边界。 */
        /* 错误边界的工作方式类似于 JavaScript 的 catch {}，不同的地方在于错误边界只针对 React 组件。只有 class 组件才可以成为错误边界组件。 错误边界只可以捕获其子组件的错误 无法捕获其自身的错误*/
        static getDerivedStateFromError(error) {
          // 更新 state 使下一次渲染能够显示降级后的 UI
          return { hasError: true };
        }

        componentDidCatch(error, errorInfo) {
          // 你同样可以将错误日志上报给服务器
          logErrorToMyService(error, errorInfo);
        }

        render() {
          if (this.state.hasError) {
            // 你可以自定义降级后的 UI 并渲染
            return <h1>Something went wrong.</h1>;
          }

          return this.props.children;
        }
      }
      /* 错误边界和try/catch
      try/catch仅能用于命令式代码 而react组件是声明式的
      错误边界保留了react的声明性质
       */
    </script>
  </body>
</html>
